module.exports = [
  {
    filmtv_ID: 2,
    film_title: "Bugs Bunny's Third Movie: 1001 Rabbit Tales",
    year: 1982,
    genre: 'Animation',
    duration: 76,
    country: 'United States',
    director: 'David Detiege, Art Davis, Bill Perez',
    actors: 'N/A',
    avg_vote: 7.7,
    votes: 28,
  },
  {
    filmtv_ID: 3,
    film_title: '18 anni tra una settimana',
    year: 1991,
    genre: 'Drama',
    duration: 98,
    country: 'Italy',
    director: 'Luigi Perelli',
    actors:
      'Kim Rossi Stuart, Simona Cavallari, Ennio Fantastichini, Orso Maria Guerrini',
    avg_vote: 7,
    votes: 3,
  },
  {
    filmtv_ID: 17,
    film_title: 'Ride a Wild Pony',
    year: 1976,
    genre: 'Romantic',
    duration: 91,
    country: 'United States',
    director: 'Don Chaffey',
    actors: 'Michael Craig, John Meillon, Eva Griffith, Graham Rouse',
    avg_vote: 5.6,
    votes: 10,
  },
  {
    filmtv_ID: 18,
    film_title: 'Diner',
    year: 1982,
    genre: 'Comedy',
    duration: 95,
    country: 'United States',
    director: 'Barry Levinson',
    actors: 'Mickey Rourke, Steve Guttenberg, Ellen Barkin',
    avg_vote: 7.1,
    votes: 14,
  },
  {
    filmtv_ID: 20,
    film_title: 'A che servono questi quattrini?',
    year: 1942,
    genre: 'Comedy',
    duration: 85,
    country: 'Italy',
    director: 'Esodo Pratelli',
    actors:
      'Eduardo De Filippo, Peppino De Filippo, Clelia Matania, Paolo Stoppa',
    avg_vote: 5.9,
    votes: 12,
  },
  {
    filmtv_ID: 21,
    film_title: 'The Uranian Conspiracy',
    year: 1978,
    genre: 'Spy',
    duration: 117,
    country: 'Italy, Germany, Israel',
    director: 'Gianfranco Baldanello, Menahem Golan',
    actors: 'Fabio Testi, Janet Agren',
    avg_vote: 5,
    votes: 2,
  },
  {
    filmtv_ID: 22,
    film_title: 'A ciascuno il suo',
    year: 1967,
    genre: 'Drama',
    duration: 93,
    country: 'Italy',
    director: 'Elio Petri',
    actors: 'Gian Maria Volonté, Irene Papas, Gabriele Ferzetti, Salvo Randone',
    avg_vote: 7.8,
    votes: 98,
  },
  {
    filmtv_ID: 23,
    film_title: 'Dead-Bang',
    year: 1989,
    genre: 'Crime',
    duration: 109,
    country: 'United States',
    director: 'John Frankenheimer',
    actors: 'Don Johnson, Penelope Ann Miller, William Forsythe, Bob Balaban',
    avg_vote: 6,
    votes: 17,
  },
  {
    filmtv_ID: 24,
    film_title: 'A... come assassino',
    year: 1966,
    genre: 'Thriller',
    duration: 80,
    country: 'Italy',
    director: 'Ray Morrison (Angelo Dorigo)',
    actors:
      'Alan Steel, Mary Arden, Sergio Ciani, Ivano Davoli, Giovanna Galletti',
    avg_vote: 6.5,
    votes: 3,
  },
  {
    filmtv_ID: 26,
    film_title: 'At Close Range',
    year: 1986,
    genre: 'Drama',
    duration: 115,
    country: 'United States',
    director: 'James Foley',
    actors: 'Christopher Walken, Sean Penn, Chris Penn, Mary Stuart Masterson',
    avg_vote: 7.5,
    votes: 82,
  },
  {
    filmtv_ID: 30,
    film_title: 'A Ghentar si muore facile',
    year: 1968,
    genre: 'Adventure',
    duration: 101,
    country: 'Italy',
    director: 'Leon Klimovsky',
    actors: 'George Hilton, Ennio Girolami, Marta Padovan, Alfonso De La Vega',
    avg_vote: 5.5,
    votes: 2,
  },
  {
    filmtv_ID: 31,
    film_title: 'Does This Mean We are Married?',
    year: 1990,
    genre: 'Comedy',
    duration: 90,
    country: 'United States',
    director: 'Carol Wiseman',
    actors: 'Patsy Kensit, Stéphane Freiss, Mouss Diouf, Anne-Marie Pisani',
    avg_vote: 4,
    votes: 1,
  },
  {
    filmtv_ID: 32,
    film_title: 'Sleeping with the Enemy',
    year: 1990,
    genre: 'Drama',
    duration: 96,
    country: 'United States',
    director: 'Joseph Ruben',
    actors:
      'Julia Roberts, Patrick Bergin, Kevin Anderson, Elizabeth Lawrence, Kyle Secor',
    avg_vote: 5,
    votes: 89,
  },
  {
    filmtv_ID: 33,
    film_title: 'Love Kills',
    year: 1991,
    genre: 'Thriller',
    duration: 100,
    country: 'United States',
    director: 'Brian Grant',
    actors: 'Virginia Madsen, Lenny Von Dohlen, Jim Metzler, Erich Anderson',
    avg_vote: 8,
    votes: 2,
  },
  {
    filmtv_ID: 34,
    film_title: 'In Bed With Madonna',
    year: 1990,
    genre: 'Documentary',
    duration: 111,
    country: 'United States',
    director: 'Alek Keshishian',
    actors: 'Madonna, Warren Beatty, Sandra Bernhard',
    avg_vote: 5.1,
    votes: 20,
  },
  {
    filmtv_ID: 35,
    film_title: 'Make Mine Mink',
    year: 1960,
    genre: 'Comedy',
    duration: 100,
    country: 'Great Britain',
    director: 'Robert Asher',
    actors: 'Terry-Thomas, Athene Seyler, Billie Withelaw, Hattie Jacques',
    avg_vote: 8,
    votes: 2,
  },
  {
    filmtv_ID: 36,
    film_title: 'Bowery at Midnight',
    year: 1942,
    genre: 'Horror',
    duration: 62,
    country: 'United States',
    director: 'Wallace Fox',
    actors: "Bela Lugosi, John Archer, Wanda McKay, Dave O'Brien, Lew Kelly",
    avg_vote: 5.7,
    votes: 15,
  },
  {
    filmtv_ID: 37,
    film_title: 'A mezzanotte va la ronda del piacere',
    year: 1975,
    genre: 'Comedy',
    duration: 100,
    country: 'Italy',
    director: 'Marcello Fondato',
    actors:
      'Claudia Cardinale, Monica Vitti, Vittorio Gassman, Giancarlo Giannini, Renato Pozzetto',
    avg_vote: 6,
    votes: 40,
  },
  {
    filmtv_ID: 38,
    film_title: 'Mr. Majestyk',
    year: 1974,
    genre: 'Action',
    duration: 105,
    country: 'United States',
    director: 'Richard Fleischer',
    actors: 'Charles Bronson, Linda Cristal, Al Lettieri, Lee Purcell',
    avg_vote: 6,
    votes: 23,
  },
  {
    filmtv_ID: 39,
    film_title: 'Crazy People',
    year: 1990,
    genre: 'Comedy',
    duration: 92,
    country: 'United States',
    director: 'Tony Bill',
    actors: 'Dudley Moore, Daryl Hannah, Paul Reiser, J. T. Walsh',
    avg_vote: 6,
    votes: 3,
  },
  {
    filmtv_ID: 41,
    film_title: 'Rouge baiser',
    year: 1985,
    genre: 'Drama',
    duration: 110,
    country: 'France',
    director: 'Véra Belmont',
    actors: 'Charlotte Valendrey, Lambert Wilson, Laurent Terzieff',
    avg_vote: 4,
    votes: 1,
  },
  {
    filmtv_ID: 42,
    film_title: 'Eldorádó',
    year: 1988,
    genre: 'Drama',
    duration: 110,
    country: 'Hungary',
    director: 'Géza Bereményi',
    actors:
      'Károly Eperjes, Judit Pogány, Péter Andorai, Géza Balkay, Enikö Eszenyi',
    avg_vote: 8,
    votes: 1,
  },
  {
    filmtv_ID: 43,
    film_title: 'À pied, à cheval, en voiture',
    year: 1957,
    genre: 'Comedy',
    duration: 100,
    country: 'France',
    director: 'Maurice Delbez',
    actors:
      'Nöel Nöel, Denis Grey, Gil Vidal, Jean-Pierre Cassel, Edmond Ardisson',
    avg_vote: 6,
    votes: 1,
  },
  {
    filmtv_ID: 44,
    film_title: 'Main pleine',
    year: 1989,
    genre: 'Thriller',
    duration: 89,
    country: 'France',
    director: 'Laurent Heynemann',
    actors: 'Christine Pascal, Gérard Darmon, Ninetto Davoli, Christophe Odent',
    avg_vote: 6,
    votes: 1,
  },
  {
    filmtv_ID: 45,
    film_title: 'Warning Sign',
    year: 1985,
    genre: 'Action',
    duration: 99,
    country: 'United States',
    director: 'Hal Barwood',
    actors: 'Sam Waterson, Kathleen Quinlan, Yaphet Kotto,Jeffrey DeMunn',
    avg_vote: 4.5,
    votes: 9,
  },
  {
    filmtv_ID: 46,
    film_title: 'Prague',
    year: 1992,
    genre: 'Drama',
    duration: 88,
    country: 'France, Great Britain',
    director: 'Ian Sellar',
    actors: 'Alan Cumming, Sandrine Bonnaire, Bruno Ganz',
    avg_vote: 6,
    votes: 1,
  },
  {
    filmtv_ID: 47,
    film_title: 'About Last Night',
    year: 1986,
    genre: 'Comedy',
    duration: 113,
    country: 'United States',
    director: 'Edward Zwick',
    actors: 'Rob Lowe, Demi Moore, James Belushi, Elizabeth Perkins',
    avg_vote: 5.8,
    votes: 29,
  },
  {
    filmtv_ID: 49,
    film_title: 'Fail-Safe',
    year: 1964,
    genre: 'Drama',
    duration: 110,
    country: 'United States',
    director: 'Sidney Lumet',
    actors: "Henry Fonda, Dan O'Herlihy, Walter Matthau, Dom DeLuise",
    avg_vote: 8.3,
    votes: 67,
  },
  {
    filmtv_ID: 50,
    film_title: 'Free Fighter',
    year: 1990,
    genre: 'Action',
    duration: 88,
    country: 'United States, China',
    director: 'Liu Chia Yung',
    actors: 'Cynthia Rothrock, Mark Huston, Tong Chung, Shing Fulon',
    avg_vote: 7,
    votes: 2,
  },
  {
    filmtv_ID: 51,
    film_title: 'Some Like It Hot',
    year: 1959,
    genre: 'Comedy',
    duration: 120,
    country: 'United States',
    director: 'Billy Wilder',
    actors: 'Tony Curtis, Jack Lemmon, Marilyn Monroe, Joe E. Brown',
    avg_vote: 9.2,
    votes: 515,
  },
  {
    filmtv_ID: 53,
    film_title: 'A qualsiasi prezzo',
    year: 1968,
    genre: 'Adventure',
    duration: 94,
    country: 'Italy',
    director: 'Emilio Miraglia',
    actors: 'Walter Pidgeon, Ira Fürstenberg, Klaus Kinski, Tino Carraro',
    avg_vote: 2.5,
    votes: 3,
  },
  {
    filmtv_ID: 54,
    film_title: "Johnny O'Clock",
    year: 1947,
    genre: 'Thriller',
    duration: 95,
    country: 'United States',
    director: 'Robert Rossen',
    actors: 'Dick Powell, Evelyn Keyes, Lee J. Cobb, Ellen Drew, Nina Foch',
    avg_vote: 8,
    votes: 17,
  },
  {
    filmtv_ID: 55,
    film_title: 'Back to School',
    year: 1986,
    genre: 'Comedy',
    duration: 100,
    country: 'United States',
    director: 'Alan Metter',
    actors:
      'Rodney Dangerfield, Keith Gordon, Sally Kellerman, Robert Downey jr.',
    avg_vote: 6.6,
    votes: 16,
  },
  {
    filmtv_ID: 56,
    film_title: 'Ninja Academy',
    year: 1988,
    genre: 'Comedy',
    duration: 89,
    country: 'United States',
    director: 'Nico Mastorakis',
    actors: 'Will Egan, Gerald Okamura, Kelly Randall, Kathleen Stevens',
    avg_vote: 4,
    votes: 1,
  },
  {
    filmtv_ID: 57,
    film_title: 'Maid To Order',
    year: 1987,
    genre: 'Comedy',
    duration: 96,
    country: 'United States',
    director: 'Amy Jones',
    actors: "Ally Sheedy, Beverly D'Angelo, Valerie Perrine, Michael Ontkean",
    avg_vote: 6,
    votes: 1,
  },
  {
    filmtv_ID: 58,
    film_title: 'Driving Miss Daisy',
    year: 1989,
    genre: 'Comedy',
    duration: 100,
    country: 'United States',
    director: 'Bruce Beresford',
    actors: 'Jessica Tandy, Morgan Freeman, Dan Aykroyd, Patty LuPone',
    avg_vote: 7.1,
    votes: 140,
  },
  {
    filmtv_ID: 59,
    film_title: 'Enid Is Sleeping',
    year: 1989,
    genre: 'Comedy',
    duration: 102,
    country: 'United States',
    director: 'Maurice Phillips',
    actors:
      'Elizabeth Perkins, Judge Reinhold, Maurine Mueller, Michael J. Pollard',
    avg_vote: 6.5,
    votes: 3,
  },
  {
    filmtv_ID: 60,
    film_title: 'South of Reno',
    year: 1987,
    genre: 'Drama',
    duration: 98,
    country: 'Great Britain',
    director: 'Mark Rezyka',
    actors: 'Jeff Osterhage, Lisa Blount, Lewis Van Bergen',
    avg_vote: 4,
    votes: 1,
  },
  {
    filmtv_ID: 61,
    film_title: 'The Appaloosa',
    year: 1966,
    genre: 'Western',
    duration: 98,
    country: 'United States',
    director: 'Sidney J. Furie',
    actors:
      'Marlon Brando, Anjanette Comer, John Saxon, Emilio Fernández, Alex Montoya',
    avg_vote: 7,
    votes: 22,
  },
  {
    filmtv_ID: 62,
    film_title: 'Table for Five',
    year: 1983,
    genre: 'Drama',
    duration: 117,
    country: 'United States',
    director: 'Robert Lieberman',
    actors:
      'Jon Voight, Richard Crenna, Marie-Christine Barrault, Kevin Costner',
    avg_vote: 6,
    votes: 1,
  },
  {
    filmtv_ID: 63,
    film_title: '...a tutte le auto della polizia...',
    year: 1975,
    genre: 'Crime',
    duration: 100,
    country: 'Italy',
    director: 'Mario Caiano',
    actors:
      'Antonio Sabàto, Luciana Paluzzi, Gabriele Ferzetti, Enrico Maria Salerno',
    avg_vote: 5.5,
    votes: 24,
  },
  {
    filmtv_ID: 64,
    film_title: 'A tutte le volanti',
    year: 1991,
    genre: 'Crime',
    duration: 85,
    country: 'Italy',
    director: 'Romolo Guerrieri',
    actors: 'Tony Palazzo, Massimiliano Pazzaglia',
    avg_vote: 4,
    votes: 1,
  },
  {
    filmtv_ID: 65,
    film_title: 'Gas',
    year: 1981,
    genre: 'Comedy',
    duration: 94,
    country: 'Canada',
    director: 'Les Rose',
    actors: 'Donald Sutherland, Sterling Hayden, Susan Anspach, Howie Mandel',
    avg_vote: 4,
    votes: 1,
  },
  {
    filmtv_ID: 66,
    film_title: 'A Matter of Degrees',
    year: 1989,
    genre: 'Comedy',
    duration: 100,
    country: 'United States',
    director: 'W.T. Morgan',
    actors:
      'Arye Gross, Judith Hoag, Tom Sizemore, Sarah Bork, Michael Balcanoff',
    avg_vote: 6,
    votes: 1,
  },
  {
    filmtv_ID: 67,
    film_title: "You'll Like My Mother",
    year: 1973,
    genre: 'Thriller',
    duration: 94,
    country: 'United States',
    director: 'Lamont Johnson',
    actors: 'Patty Duke, Rosemary Murphy, Richard Thomas',
    avg_vote: 8,
    votes: 2,
  },
  {
    filmtv_ID: 68,
    film_title: 'Abbasso la miseria!',
    year: 1945,
    genre: 'Comedy',
    duration: 90,
    country: 'Italy',
    director: 'Gennaro Righelli',
    actors: 'Anna Magnani, Nino Besozzi, Virgilio Riento, Lauro Gazzolo',
    avg_vote: 6,
    votes: 29,
  },
  {
    filmtv_ID: 69,
    film_title: 'Abbasso la ricchezza!',
    year: 1946,
    genre: 'Comedy',
    duration: 93,
    country: 'Italy',
    director: 'Gennaro Righelli',
    actors: 'Anna Magnani, Vittorio De Sica, Virgilio Riento, Galeazzo Benti',
    avg_vote: 5.7,
    votes: 30,
  },
  {
    filmtv_ID: 70,
    film_title: 'Can You Feel Me Dancing?',
    year: 1986,
    genre: 'Drama',
    duration: 120,
    country: 'United States',
    director: 'Michael Miller',
    actors: 'Justine Bateman, Jason Bateman, Max Gail, Joe Nasser',
    avg_vote: 6,
    votes: 1,
  },
  {
    filmtv_ID: 71,
    film_title: 'Charlie Muffin',
    year: 1979,
    genre: 'Spy',
    duration: 109,
    country: 'Great Britain',
    director: 'Jack Gold',
    actors:
      'David Hemmings, Sam Wanamaker, Jennie Linden, Ian Richardson, Ralph Richardson',
    avg_vote: 6.1,
    votes: 11,
  },
  {
    filmtv_ID: 72,
    film_title: 'Final Embrace',
    year: 1992,
    genre: 'Thriller',
    duration: 98,
    country: 'United States',
    director: 'Oley Sassone',
    actors: 'Robert Rusler, Nancy Valen, Dick Van Patten, Dee McCafferty',
    avg_vote: 4,
    votes: 1,
  },
  {
    filmtv_ID: 73,
    film_title: 'Abbronzatissimi',
    year: 1991,
    genre: 'Comedy',
    duration: 114,
    country: 'Italy',
    director: 'Bruno Gaburro',
    actors: 'Jerry Calà, Alba Parietti, Eva Grimaldi, Teo Teocoli',
    avg_vote: 3.4,
    votes: 75,
  },
  {
    filmtv_ID: 74,
    film_title: 'The Deep',
    year: 1977,
    genre: 'Adventure',
    duration: 130,
    country: 'United States',
    director: 'Peter Yates',
    actors:
      'Nick Nolte, Jacqueline Bisset, Robert Shaw, Eli Wallach, Louis Gossett jr.',
    avg_vote: 5.1,
    votes: 28,
  },
  {
    filmtv_ID: 75,
    film_title: 'Strangers: the Story of a Mother and Daughter',
    year: 1979,
    genre: 'Drama',
    duration: 120,
    country: 'United States',
    director: 'Milton Katselas',
    actors: 'Bette Davis, Gena Rowlands, Ford Rainey, Donald Moffat',
    avg_vote: 8,
    votes: 2,
  },
  {
    filmtv_ID: 76,
    film_title: "L'abito nero da sposa",
    year: 1945,
    genre: 'History',
    duration: 90,
    country: 'Italy',
    director: 'Luigi Zampa',
    actors:
      'Fosco Giachetti, Jacqueline Laurent, Carlo Tamberlani, Enzo Fiermonte',
    avg_vote: 7,
    votes: 2,
  },
  {
    filmtv_ID: 77,
    film_title: 'Abe Lincoln in Illinois',
    year: 1940,
    genre: 'Biography',
    duration: 110,
    country: 'United States',
    director: 'John Cromwell',
    actors: 'Raymond Massey, Ruth Gordon, Gene Lockhart',
    avg_vote: 6.3,
    votes: 8,
  },
  {
    filmtv_ID: 78,
    film_title: 'Absolute Beginners',
    year: 1986,
    genre: 'Musical',
    duration: 100,
    country: 'Great Britain',
    director: 'Julien Temple',
    actors: "Patsy Kensit, David Bowie, Eddie O'Connell",
    avg_vote: 6.4,
    votes: 27,
  },
  {
    filmtv_ID: 79,
    film_title: 'The Abyss',
    year: 1989,
    genre: 'Fantasy',
    duration: 138,
    country: 'United States',
    director: 'James Cameron',
    actors: 'Ed Harris, Mary Elizabeth Mastrantonio, Michael Biehn',
    avg_vote: 7.2,
    votes: 178,
  },
  {
    filmtv_ID: 80,
    film_title: 'Acapulco, prima spiaggia... a sinistra',
    year: 1983,
    genre: 'Comedy',
    duration: 88,
    country: 'Italy',
    director: 'Sergio Martino',
    actors:
      'Gigi Sammarchi, Andrea Roncato, Simona Marchini, Gegia, Anna Kanakis',
    avg_vote: 4.1,
    votes: 71,
  },
  {
    filmtv_ID: 82,
    film_title: 'Accadde a Damasco',
    year: 1943,
    genre: 'Comedy',
    duration: 88,
    country: 'Italy, Spain',
    director: 'José López Rubio, Primo Zeglio',
    actors: 'Paola Barbara, Germana Paolieri, Miguel Ligero, Lauro Gazzolo',
    avg_vote: 3.5,
    votes: 3,
  },
  {
    filmtv_ID: 83,
    film_title: 'Accadde al penitenziario',
    year: 1955,
    genre: 'Comedy',
    duration: 95,
    country: 'Italy',
    director: 'Giorgio Bianchi',
    actors:
      'Aldo Fabrizi, Walter Chiari, Alberto Sordi, Peppino De Filippo, Mara Berni, Nino Besozzi',
    avg_vote: 5.4,
    votes: 37,
  },
  {
    filmtv_ID: 84,
    film_title: 'It Happened Tomorrow',
    year: 1944,
    genre: 'Comedy',
    duration: 84,
    country: 'United States',
    director: 'René Clair',
    actors:
      'Dick Powell, Linda Darnell, Jack Oakie, Edgard Kennedy, John Philliber',
    avg_vote: 7.5,
    votes: 52,
  },
  {
    filmtv_ID: 85,
    film_title: 'Es geschah am 20. Juli',
    year: 1955,
    genre: 'War',
    duration: 75,
    country: 'Germany',
    director: 'Georg Wilhelm Pabst',
    actors:
      'Bernhard Wicki, Karl Ludwig Diehl, Carl Wery, Kurt Meisel, Erik Frey',
    avg_vote: 6,
    votes: 1,
  },
  {
    filmtv_ID: 86,
    film_title: 'It Happened in Athens',
    year: 1962,
    genre: 'Comedy',
    duration: 92,
    country: 'United States',
    director: 'Andrew Marton',
    actors: 'Jayne Mansfield, Trax Colton',
    avg_vote: 6.5,
    votes: 3,
  },
  {
    filmtv_ID: 87,
    film_title: 'Made in Heaven',
    year: 1987,
    genre: 'Romantic',
    duration: 102,
    country: 'United States',
    director: 'Alan Rudolph',
    actors: 'Timothy Hutton, Kelly McGillis, Maureen Stapleton, Tom Petty',
    avg_vote: 5.8,
    votes: 18,
  },
  {
    filmtv_ID: 88,
    film_title: 'September Affair',
    year: 1950,
    genre: 'Comedy',
    duration: 104,
    country: 'United States',
    director: 'William Dieterle',
    actors: 'Joan Fontaine, Joseph Cotten, Françoise Rosay',
    avg_vote: 7.2,
    votes: 4,
  },
  {
    filmtv_ID: 89,
    film_title: 'It Happened One Night',
    year: 1934,
    genre: 'Comedy',
    duration: 108,
    country: 'United States',
    director: 'Frank Capra',
    actors: 'Clark Gable, Claudette Colbert, Walter Connolly, Roscoe Karns',
    avg_vote: 8.6,
    votes: 157,
  },
  {
    filmtv_ID: 90,
    film_title: "All's Fair",
    year: 1989,
    genre: 'Comedy',
    duration: 89,
    country: 'United States',
    director: 'Rocky Lane',
    actors: 'George Seagal, Sally Kellerman, Robert Carradine',
    avg_vote: 2,
    votes: 3,
  },
  {
    filmtv_ID: 91,
    film_title: 'Mortuary Academy',
    year: 1988,
    genre: 'Comedy',
    duration: 90,
    country: 'United States',
    director: 'Michael Schroeder',
    actors: 'Christopher Atkins, Perry Lang, Paul Bartel, Mary Woronov',
    avg_vote: 6,
    votes: 1,
  },
  {
    filmtv_ID: 92,
    film_title: 'Accattone',
    year: 1961,
    genre: 'Drama',
    duration: 120,
    country: 'Italy',
    director: 'Pier Paolo Pasolini',
    actors: 'Franco Citti, Franca Pasut, Adriana Asti, Paola Guidi',
    avg_vote: 8.8,
    votes: 241,
  },
  {
    filmtv_ID: 93,
    film_title: 'Gridlock',
    year: 1980,
    genre: 'Comedy',
    duration: 97,
    country: 'United States',
    director: 'James Frawley',
    actors:
      'Desi Arnaz jr., Lisa Hartman, John Beck, William Bryant, Rod Burton',
    avg_vote: 6,
    votes: 1,
  },
  {
    filmtv_ID: 94,
    film_title: 'Arrêt sur image',
    year: 1987,
    genre: 'Drama',
    duration: 77,
    country: 'France',
    director: 'Christine Allen',
    actors: 'Valérie Dumas, Marvin Sither',
    avg_vote: 4.8,
    votes: 3,
  },
  {
    filmtv_ID: 95,
    film_title: 'Achtung! Banditi!',
    year: 1951,
    genre: 'War',
    duration: 100,
    country: 'Italy',
    director: 'Carlo Lizzani',
    actors: 'Andrea Checchi, Lamberto Maggiorani, Gina Lollobrigida',
    avg_vote: 6.9,
    votes: 48,
  },
  {
    filmtv_ID: 96,
    film_title: 'Acqua cheta',
    year: 1933,
    genre: 'Comedy',
    duration: 68,
    country: 'Italy',
    director: 'Gero Zambuto',
    actors: 'Gianfranco Giachetti, Andreina Pagnani, Germana Paolieri',
    avg_vote: 8,
    votes: 1,
  },
  {
    filmtv_ID: 97,
    film_title: 'Water',
    year: 1985,
    genre: 'Grotesque',
    duration: 97,
    country: 'Great Britain',
    director: 'Dick Clement',
    actors: 'Michael Caine, Valerie Perrine, Brenda Vaccaro',
    avg_vote: 6.7,
    votes: 6,
  },
  {
    filmtv_ID: 100,
    film_title: 'Acque di primavera',
    year: 1942,
    genre: 'Drama',
    duration: 80,
    country: 'Italy',
    director: 'Nunzio Malasomma',
    actors:
      'Gino Cervi, Mariella Lotti, Paolo Stoppa, Vanna Vanni, Carlo Lombardi',
    avg_vote: 5.5,
    votes: 3,
  },
  {
    filmtv_ID: 101,
    film_title: 'Action Jackson',
    year: 1988,
    genre: 'Crime',
    duration: 97,
    country: 'United States',
    director: 'Craig R. Baxley',
    actors: 'Carl Weathers, Craig T. Nelson, Vanity, Sharon Stone',
    avg_vote: 5,
    votes: 32,
  },
  {
    filmtv_ID: 102,
    film_title: 'Shi no Toge',
    year: 1990,
    genre: 'Drama',
    duration: 115,
    country: 'Japan',
    director: 'Koei Oguri',
    actors: 'Keiko Matsuzaka, Ittoku Kishibe, Takenori Matsumura',
    avg_vote: 8,
    votes: 1,
  },
  {
    filmtv_ID: 103,
    film_title: 'East of Elephant Rock',
    year: 1977,
    genre: 'Drama',
    duration: 92,
    country: 'Great Britain',
    director: 'John Boyd',
    actors: 'John Hurt, Judy Bowker, Jeremy Kemp, Christopher Cazenove',
    avg_vote: 4,
    votes: 1,
  },
  {
    filmtv_ID: 104,
    film_title: 'Mail Order Bride',
    year: 1963,
    genre: 'Western',
    duration: 90,
    country: 'United States',
    director: 'Burt Kennedy',
    actors:
      'Buddy Ebsen, Keir Dullea, Warren Oates, Marie Windsor, Lois Nettleton, Barbara Luna',
    avg_vote: 6.3,
    votes: 13,
  },
  {
    filmtv_ID: 105,
    film_title: 'Ad Ovest di Paperino',
    year: 1982,
    genre: 'Comedy',
    duration: 95,
    country: 'Italy',
    director: 'Alessandro Benvenuti',
    actors: 'Alessandro Benvenuti, Francesco Nuti, Athina Cenci',
    avg_vote: 6.5,
    votes: 71,
  },
  {
    filmtv_ID: 107,
    film_title: 'Ada',
    year: 1961,
    genre: 'Drama',
    duration: 109,
    country: 'United States',
    director: 'Daniel Mann',
    actors: 'Susan Hayward, Dean Martin, Wilfrid Hyde-White',
    avg_vote: 6.8,
    votes: 5,
  },
  {
    filmtv_ID: 108,
    film_title: 'Adamo ed Eva',
    year: 1949,
    genre: 'Comedy',
    duration: 90,
    country: 'Italy',
    director: 'Mario Mattòli',
    actors: 'Erminio Macario, Isa Barzizza, Gianni Agus',
    avg_vote: 4.8,
    votes: 8,
  },
  {
    filmtv_ID: 109,
    film_title: 'Adam and Evelyne',
    year: 1949,
    genre: 'Comedy',
    duration: 92,
    country: 'Great Britain',
    director: 'Harold French',
    actors: 'Stewart Granger, Jean Simmons, Helen Cherry',
    avg_vote: 7.1,
    votes: 11,
  },
  {
    filmtv_ID: 110,
    film_title: 'Farewell to the King',
    year: 1988,
    genre: 'War',
    duration: 107,
    country: 'United States',
    director: 'John Milius',
    actors: 'Nick Nolte, Nigel Havers, James Fox, Frank McRae, Marilyn Toduka',
    avg_vote: 6.8,
    votes: 38,
  },
  {
    filmtv_ID: 111,
    film_title: 'A Farewell to Arms',
    year: 1932,
    genre: 'War',
    duration: 78,
    country: 'United States',
    director: 'Frank Borzage',
    actors: 'Gary Cooper, Helen Hayes, Adolphe Menjou, Mary Philips',
    avg_vote: 6.5,
    votes: 15,
  },
  {
    filmtv_ID: 113,
    film_title: 'Good Night Sweet Wife: A Murder in Boston',
    year: 1990,
    genre: 'Thriller',
    duration: 100,
    country: 'United States',
    director: 'Jerrold Freedman',
    actors: 'Ken Olin, Margaret Colin, Annabella Price',
    avg_vote: 6,
    votes: 1,
  },
  {
    filmtv_ID: 114,
    film_title: 'Addio giovinezza!',
    year: 1940,
    genre: 'Drama',
    duration: 88,
    country: 'Italy',
    director: 'Ferdinando M. Poggioli',
    actors: 'Maria Denis, Adriano Rimoldi, Clara Calamai',
    avg_vote: 7,
    votes: 11,
  },
  {
    filmtv_ID: 115,
    film_title: 'Goodbye, My Lady',
    year: 1956,
    genre: 'Drama',
    duration: 95,
    country: 'United States',
    director: 'William A. Wellman',
    actors: 'Brandon De Wilde, Walter Brennan, Sidney Poitier',
    avg_vote: 6,
    votes: 3,
  },
];
